### ISSUE TITLE
TypeError: bundle.modules.indexOf is not a function

### ISSUE THREAD

**Issue by mycarrysun** [danburzo/rollup-plugin-css-bundle#1]
I've got a pretty basic import structure right now for my css bundle - importing 3 files in the entry index.js
```javascript
import './quasar.mat.css'
import './styles.styl'
import './styles.scss'
```
And here is my rollup config:
```javascript
import autoprefixer from 'autoprefixer'
import postcss from 'postcss'
import copy from 'rollup-plugin-copy'
import url from 'postcss-url'
import cssbundle from 'rollup-plugin-css-bundle'
import postcssSyntax from 'postcss-syntax'

export default {
  //...
  plugins: [
    cssbundle({
      include: [
        '**/*.css',
        '**/*.styl',
        '**/*.scss'
      ],
      exclude: [
        'node_modules/**',
        'dist/**',
      ],
      output: 'dist/styles.css',
      transform: code => postcss([
        autoprefixer,
        url,
      ]).process(code, {
        syntax: postcssSyntax
      })
    }),
  ]
  //...
}
```

Error happening [here](https://github.com/Evercoder/rollup-plugin-css-bundle/blob/a52df8b8c3d6986585cd42c08c3e423627a56b08/src/index.js#L33)

**Comment by danburzo** [comment]
Thanks for reporting this! Seems the signature for `ongenerate` has [changed in the meantime](https://github.com/rollup/rollup/commit/2b0b6c9715c8f675927519f90667c9171f3e8a6a#diff-c5fd8e65630bd641bf07130346ee8778).

**Comment by danburzo** [comment]
@mycarrysun can you let me know which exact version of Rollup you're using? (`npx rollup -v` should show it)

**Comment by mycarrysun** [comment]
Going to go back to ^0.59.4 so it will work for now

**Comment by danburzo** [comment]
(The comment about the `ongenerate` signature might have been a false alarm) — I set up a simple rollup config similar to yours and was not able to reproduce the error on the latest Rollup...

**Comment by mycarrysun** [comment]
@danburzo weird...cause when I reverted to 0.59.4 it compiled correctly. Although I am now currently using dnjstrom's branch of rollup-plugin-postcss to achieve the same effect.
